In [4]:
import scipy.optimize as optimize
import numpy as np

In [7]:
def f(a, b):
    print(params)  # <-- you'll see that params is a NumPy array
    a, b, c, d, e, f = params # <-- for readability you may wish to assign names to the component variables
    return (a*b+ c*d + e*f - 1.0)**2

initial_guess = [1,1,1,1,1,1]
result = optimize.minimize(f, initial_guess)
if result.success:
    fitted_params = result.x
    print(fitted_params)
else:
    raise ValueError(result.message)

[ 1.  1.  1.  1.  1.  1.]
[ 1.00000001  1.          1.          1.          1.          1.        ]
[ 1.          1.00000001  1.          1.          1.          1.        ]
[ 1.          1.          1.00000001  1.          1.          1.        ]
[ 1.          1.          1.          1.00000001  1.          1.        ]
[ 1.          1.          1.          1.          1.00000001  1.        ]
[ 1.          1.          1.          1.          1.          1.00000001]
[ 1.  1.  1.  1.  1.  1.]
[ 0.58766923  0.58766923  0.58766923  0.58766923  0.58766923  0.58766923]
[ 0.58766923  0.58766923  0.58766923  0.58766923  0.58766923  0.58766923]
[ 0.58766924  0.58766923  0.58766923  0.58766923  0.58766923  0.58766923]
[ 0.58766923  0.58766924  0.58766923  0.58766923  0.58766923  0.58766923]
[ 0.58766923  0.58766923  0.58766924  0.58766923  0.58766923  0.58766923]
[ 0.58766923  0.58766923  0.58766923  0.58766924  0.58766923  0.58766923]
[ 0.58766923  0.58766923  0.58766923  0.58766923  0.58766924

In [76]:
dim = 6

bound = []
for i in range(0,dim):
    bound.append((1.0,5.0))
for i in range(0,dim):
    bound.append((-np.inf,np.inf))
bnds = tuple(bound)


def f(x,s):
    
    return sum((np.dot(x[0],x[1]) - s)**2)
s = np.array([4.0, 2.0, 1.0, 5.0, 2.5, 1.67, 1.25, 1.0,
            8.33, 7.14, 6.25])
initial_guess = [np.random.uniform(1.0,5.0,dim),np.random.uniform(0.0,1.0,dim)]
result = optimize.minimize(f, initial_guess, args=(s,), method='SLSQP', bounds=bnds)
if result.success:
    fitted_params = result.x
    print(fitted_params)
    print(result.fun)
    print(result.nit)
else:
    raise ValueError(result.message)

[ 2.4320659   1.5004052   4.79993034  3.98533557  1.85211438  3.6111101
  0.08253804  0.70215608  0.87946196  0.67656377  0.24235895  0.38189019]
70.55789090956722
6


In [69]:
from scipy.optimize import least_squares
dim = 6
half = int(dim/2)

bound = []
for i in range(0,dim):
    bound.append((1.0,5.0))
for i in range(0,dim):
    bound.append((-np.inf,np.inf))
bnds = tuple(bound)

def model(x):
    return np.dot(x[:half],x[half:])
    
def fun(x,s):
    return model(x)-s

s = np.array([4.0, 2.0, 1.0, 5.0e-1, 2.5e-1, 1.67e-1, 1.25e-1, 1.0e-1,
            8.33e-2, 7.14e-2, 6.25e-2])
initial_guess = np.array([1,2,3,24,12,1])
res = least_squares(fun, initial_guess, bounds=bnds, args=(s,), verbose=1)
res.x

ValueError: `bounds` must contain 2 elements.

In [49]:
def model(x, u):
    return x[0] * (u ** 2 + x[1] * u) / (u ** 2 + x[2] * u + x[3])
def fun(x, u, y):
    return model(x, u) - y
u = np.array([4.0, 2.0, 1.0, 5.0e-1, 2.5e-1, 1.67e-1, 1.25e-1, 1.0e-1,
              8.33e-2, 7.14e-2, 6.25e-2])
y = np.array([1.957e-1, 1.947e-1, 1.735e-1, 1.6e-1, 8.44e-2, 6.27e-2,
              4.56e-2, 3.42e-2, 3.23e-2, 2.35e-2, 2.46e-2])
x0 = np.array([2.5, 3.9, 4.15, 3.9])
res = least_squares(fun, x0, bounds=(0, 100), args=(u, y), verbose=1)


res.x

`ftol` termination condition is satisfied.
Function evaluations 129, initial cost 4.4383e+00, final cost 1.5375e-04, first-order optimality 1.21e-05.


array([ 0.19280827,  0.19125228,  0.12305085,  0.13604842])